#!/bin/sh

# Download websocketd for your platform from
# https://github.com/joewalnes/websocketd/wiki/Download-and-install

 heypic \
  --ck=$TWITTER_CONSUMER_KEY \
  --cs=$TWITTER_CONSUMER_SECRET \
  --ot=$TWITTER_OAUTH_TOKEN \
  --os=$TWITTER_OAUTH_TOKEN_SECRET | \
  websocketd --port=8080 --staticdir=public server